-- Initial migration for Klaro DB (generated by agent)
-- Creates core enums and tables used by Klaro

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enums
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'document_status') THEN
        CREATE TYPE document_status AS ENUM ('uploaded','processing','analyzed','failed');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'analysis_status') THEN
        CREATE TYPE analysis_status AS ENUM ('pending','completed','error');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
        CREATE TYPE booking_status AS ENUM ('scheduled','confirmed','in_progress','completed','cancelled');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
        CREATE TYPE payment_status AS ENUM ('pending','completed','failed','refunded');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'session_type') THEN
        CREATE TYPE session_type AS ENUM ('chat_consult','video_consult','async_review');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ownership') THEN
        CREATE TYPE ownership AS ENUM ('public','private');
    END IF;
END $$;

-- Users (auth schema expected to exist). Create basic users table if missing.
CREATE TABLE IF NOT EXISTS "user" (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text,
  email text UNIQUE,
  email_verified boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Documents
CREATE TABLE IF NOT EXISTS document (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  file_name varchar(255) NOT NULL,
  mime_type varchar(100),
  file_size integer,
  storage_url text,
  status document_status NOT NULL DEFAULT 'uploaded',
  ocr_text text,
  confidence numeric(3,2),
  ocr_source varchar(20),
  ocr_audit jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS document_user_id_idx ON document(user_id);
CREATE INDEX IF NOT EXISTS document_status_idx ON document(status);

-- Analysis
CREATE TABLE IF NOT EXISTS analysis (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  extracted_fields jsonb,
  flagged_values jsonb,
  plain_language_summary text,
  tanqmo_card jsonb,
  status analysis_status NOT NULL DEFAULT 'pending',
  error_message text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS analysis_document_id_idx ON analysis(document_id);
CREATE INDEX IF NOT EXISTS analysis_user_id_idx ON analysis(user_id);

-- Chat messages
CREATE TABLE IF NOT EXISTS chat_message (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  analysis_id uuid NOT NULL REFERENCES analysis(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  role varchar(20) NOT NULL,
  content text NOT NULL,
  dialect varchar(50) DEFAULT 'Filipino',
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS chat_message_analysis_id_idx ON chat_message(analysis_id);
CREATE INDEX IF NOT EXISTS chat_message_user_id_idx ON chat_message(user_id);

-- Doctors
CREATE TABLE IF NOT EXISTS doctor (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  specialization varchar(255) NOT NULL,
  license_number varchar(100) NOT NULL UNIQUE,
  prc_status varchar(50) DEFAULT 'pending',
  bio text,
  profile_image_url text,
  price_per_session numeric(8,2) NOT NULL,
  available_session_types jsonb,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS doctor_user_id_idx ON doctor(user_id);
CREATE INDEX IF NOT EXISTS doctor_prc_status_idx ON doctor(prc_status);

-- Facilities
CREATE TABLE IF NOT EXISTS facility (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(255) NOT NULL,
  facility_type varchar(100),
  ownership ownership NOT NULL DEFAULT 'private',
  address text NOT NULL,
  latitude numeric(10,8),
  longitude numeric(11,8),
  phone_number varchar(20),
  is_philhealth_accredited boolean DEFAULT false,
  accepted_specialties jsonb,
  opening_hours jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS facility_location_idx ON facility(latitude, longitude);
CREATE INDEX IF NOT EXISTS facility_type_idx ON facility(facility_type);
CREATE INDEX IF NOT EXISTS facility_ownership_idx ON facility(ownership);

-- Bookings
CREATE TABLE IF NOT EXISTS booking (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  doctor_id uuid NOT NULL REFERENCES doctor(id) ON DELETE RESTRICT,
  document_id uuid REFERENCES document(id) ON DELETE SET NULL,
  session_type session_type NOT NULL,
  scheduled_at timestamptz NOT NULL,
  status booking_status NOT NULL DEFAULT 'scheduled',
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS booking_user_id_idx ON booking(user_id);
CREATE INDEX IF NOT EXISTS booking_doctor_id_idx ON booking(doctor_id);
CREATE INDEX IF NOT EXISTS booking_status_idx ON booking(status);

-- Payments
CREATE TABLE IF NOT EXISTS payment (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL REFERENCES booking(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  amount numeric(8,2) NOT NULL,
  currency varchar(3) DEFAULT 'PHP',
  status payment_status NOT NULL DEFAULT 'pending',
  stripe_payment_intent_id varchar(255),
  stripe_client_secret text,
  failure_reason text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS payment_booking_id_idx ON payment(booking_id);
CREATE INDEX IF NOT EXISTS payment_user_id_idx ON payment(user_id);
CREATE INDEX IF NOT EXISTS payment_status_idx ON payment(status);

-- Ensure updated_at triggers
CREATE OR REPLACE FUNCTION trigger_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach triggers for tables with updated_at
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'document_update_timestamp') THEN
    CREATE TRIGGER document_update_timestamp
    BEFORE UPDATE ON document
    FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'analysis_update_timestamp') THEN
    CREATE TRIGGER analysis_update_timestamp
    BEFORE UPDATE ON analysis
    FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'doctor_update_timestamp') THEN
    CREATE TRIGGER doctor_update_timestamp
    BEFORE UPDATE ON doctor
    FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'facility_update_timestamp') THEN
    CREATE TRIGGER facility_update_timestamp
    BEFORE UPDATE ON facility
    FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'booking_update_timestamp') THEN
    CREATE TRIGGER booking_update_timestamp
    BEFORE UPDATE ON booking
    FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'payment_update_timestamp') THEN
    CREATE TRIGGER payment_update_timestamp
    BEFORE UPDATE ON payment
    FOR EACH ROW EXECUTE FUNCTION trigger_update_timestamp();
  END IF;
END $$;

-- Migration complete

